#!/usr/bin/env python3
"""Generates InstrumentTables.cpp (cs::spec, cs::instrumentFromKey, cs::detail::radiationFor) from data/instruments/*.json (D-018).
Usage: gen_instruments.py <data-dir> <out.cpp>. Python 3 stdlib only. Fails (exit 1) if the data violate the T-001..T-003 invariants."""
import json, math, os, sys
ORDER = ["erhu", "yehu", "gaohu", "zhonghu", "banhu", "jinghu", "sihu", "matouqin", "pipa", "liuqin", "yueqin", "xiaoruan", "zhongruan",
         "daruan", "sanxian", "guzheng", "guqin", "konghou", "yangqin"]
ENUM = [k.capitalize() for k in ORDER]
FAMS = {"Bowed": "Bowed", "PluckedLute": "PluckedLute", "Zither": "Zither", "Struck": "Struck"}
MATS = {"Steel": "Steel", "Silk": "Silk", "Nylon": "Nylon", "SilkWoundSteel": "SilkWoundSteel"}
datadir, out = sys.argv[1], sys.argv[2]
def lit(x): return repr(float(x)) if not float(x).is_integer() else repr(float(x))
errors = []
data = []
for k in ORDER:
    d = json.load(open(os.path.join(datadir, "instruments", k + ".json"))); data.append(d)
    if d["key"] != k: errors.append(f"{k}: key mismatch")
    if d["family"] not in FAMS: errors.append(f"{k}: bad family")
    s = d["strings"]
    if not s: errors.append(f"{k}: no strings")
    if any(s[i + 1]["openHz"] < s[i]["openHz"] for i in range(len(s) - 1)): errors.append(f"{k}: strings not ascending")
    if not d["citations"]: errors.append(f"{k}: no citations")
    if not d["midiLow"] < d["midiHigh"]: errors.append(f"{k}: midi range")
    ncour = sum(x["courses"] for x in s)
    if not 1 <= d["maxPolyphony"] <= ncour: errors.append(f"{k}: maxPolyphony")
    for x in s:
        c = math.sqrt(x["tensionN"] / (x["densityKgM3"] * math.pi * x["radiusM"] ** 2)) / (2 * x["vibratingLengthM"])
        if abs(c / x["openHz"] - 1) > 0.005: errors.append(f"{k}: string {x['openHz']} inconsistent ({c})")
        if x["material"] not in MATS: errors.append(f"{k}: material")
if errors: print("\n".join(errors)); sys.exit(1)
o = ['// GENERATED by tools/gen_instruments.py from data/instruments/*.json — do not edit.',
     '#include "cs/Instruments.h"', '#include "InstrumentInternal.h"', '#include <array>', '#include <cstddef>', 'namespace cs {', 'namespace {',
     'using SM = StringMaterial;', 'const std::array<InstrumentSpec, %d>& table() {' % len(ORDER), '    static const std::array<InstrumentSpec, %d> t = {{' % len(ORDER)]
for e, d in zip(ENUM, data):
    o.append(f'        InstrumentSpec{{InstrumentId::{e}, Family::{FAMS[d["family"]]}, "{d["key"]}", "{d["displayName"]}", {d["maxPolyphony"]}, {"true" if d["stopsAllStringsTogether"] else "false"},')
    o.append('            {' + ",\n             ".join('StringSpec{%s, %s, %s, %s, %s, %s, %s, %s, SM::%s, %d, %s}' % (lit(x["openHz"]), lit(x["vibratingLengthM"]), lit(x["tensionN"]), lit(x["densityKgM3"]), lit(x["radiusM"]), lit(x["youngsModulusPa"]), lit(x["sigma0"]), lit(x["sigma1"]), MATS[x["material"]], x["courses"], lit(x["courseDetuneCents"])) for x in d["strings"]) + '},')
    o.append('            {' + ", ".join(lit(f) for f in d["fretSemitones"]) + '},')
    o.append('            {' + ", ".join('ModeSpec{%s, %s, %s}' % (lit(m["freqHz"]), lit(m["t60s"]), lit(m["gain"])) for m in d["bodyModes"]) + '},')
    o.append('            {},')
    o.append(f'            {d["midiLow"]}, {d["midiHigh"]},')
    o.append('            {' + ", ".join('"%s"' % c for c in d["citations"]) + '}},')
o += ['    }};', '    return t;', '}', '}  // namespace',
      'const InstrumentSpec& spec(InstrumentId id) { return table()[static_cast<std::size_t>(id)]; }',
      'std::optional<InstrumentId> instrumentFromKey(std::string_view key) {',
      '    for (const auto& s : table()) if (s.key == key) return s.id;', '    return std::nullopt;', '}']
yb = json.load(open(os.path.join(datadir, "bodies", "yehu_body.json")))
o += ['namespace detail {', 'const RadiationSpec* radiationFor(InstrumentId id) {',
      '    static const RadiationSpec yehu = {44100.0, %s, {' % lit(yb["radiationFIR"][0])]
o.append(",\n".join('        {{%s, %s, %s}, {%s, %s}}' % (lit(s["a"][0]), lit(s["a"][1]), lit(s["a"][2]), lit(s["b"][0]), lit(s["b"][1])) for s in yb["radiationParallelSections"]))
o += ['    }};', '    if (id == InstrumentId::Yehu || id == InstrumentId::Banhu) return &yehu;', '    return nullptr;', '}', '}  // namespace detail', '}  // namespace cs']
os.makedirs(os.path.dirname(out), exist_ok=True); open(out, "w").write("\n".join(o) + "\n")
print("generated", out)
